import { Article, PhotoAsset } from "./types";

export const PHOTO_ASSETS: PhotoAsset[] = [
  {
    id: "banjir_sukosewu",
    name: "Luapan Sungai Pacal (Sukosewu)",
    url: "https://images.pexels.com/photos/73821/flood-water-nature-natural-disaster-73821.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Kondisi air sungai yang membanjiri jalanan dan sawah-sawah pekarangan warga.",
    defaultCaption: "EVAKUASI BANJIR — Kondisi banjir luapan sungai yang merendam akses jalan dan pekarangan pemukiman warga di kawasan Desa Sukosewu, Kabupaten Bojonegoro, Kamis (21/5/2026).",
    defaultDraft: "Banjir parah melanda kawasan Sukosewu bojonegoro hari ini jam 3 sore. Hujan lebat dari siang bikin air sungai meluap sampai masuk ke permukiman. Ketinggian air selutut orang dewasa. Gak ada korban jiwa kata pak kades, tapi warga pada sibuk ngungsiin barang-barang."
  },
  {
    id: "kampus_unugiri",
    name: "Gedung Utama Kampus UNUGIRI",
    url: "https://images.pexels.com/photos/256490/pexels-photo-256490.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Kampus modern UNUGIRI yang megah sebagai pusat sains dan pengabdian masyarakat.",
    defaultCaption: "KAMPUS GREEN — Suasana gedung utama Universitas Nahdlatul Ulama Sunan Giri (UNUGIRI) Bojonegoro yang megah, ramah lingkungan, dan mendukung kenyamanan belajar mahasiswa.",
    defaultDraft: "Unugiri kampus kebanggaan warga bojonegoro baru aja dapet kabar gembira. Gedung barunya yang buat kegiatan rektorat udah kelar dibangun dan keliatan megah banget bergaya eco green. Rencananya mau diresmiin minggu depan sama jajaran pengurus yayasan dan pak rektor."
  },
  {
    id: "sawah_bojonegoro",
    name: "Sawah di Lereng Bojonegoro",
    url: "https://images.pexels.com/photos/162240/rice-fields-terraces-mountains-nature-162240.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Lahan pertanian padi produktif yang menjadi andalan ketahanan pangan daerah Bojonegoro.",
    defaultCaption: "SWASEMBADA PADI — Hamparan persawahan warga di wilayah pinggiran Bojonegoro yang subur dan dijaga kelestarian sistem irigasinya agar terhindar dari gagal panen.",
    defaultDraft: "Petani padi di daerah pinggiran bojonegoro lagi ketar-ketir dapet kabar bakal ada cuaca ekstrem. Mereka takut sawahnya yg baru ditanemin padi umur sebulan bakal rusak atau kebanjiran kalo kali pacal meluap lagi. Makanya mereka pada masang tanggul pasir tambahan rame-rame."
  }
];

export const INITIAL_NEWS_PORTAL: Article[] = [
  {
    id: "headline_banjir",
    title: "Diguyur Hujan Deras, Puluhan Rumah di Sukosewu Bojonegoro Terendam Banjir Luapan Sungai Pacal",
    body: "BOJONEGORO — Hujan lebat dengan intensitas tinggi yang mengguyur wilayah Kabupaten Bojonegoro selama lebih dari lima jam berturut-turut mengakibatkan luapan Sungai Pacal merendam permukiman warga di Kecamatan Sukosewu pada Kamis (21/5/2026) sore. Air dilaporkan mulai meluap dan memasuki pekarangan serta rumah-rumah warga sejak pukul 15.00 WIB akibat ketidakmampuan tanggul sungai menahan debit air yang datang dari wilayah hulu.\n\nBerdasarkan data sementara yang dihimpun dari Badan Penanggulangan Bencana Daerah (BPBD) Kabupaten Bojonegoro, setidaknya puluhan rumah warga yang tersebar di Desa Sukosewu, Desa Klepek, hingga Desa Semawot dilaporkan tergenang air. Di beberapa titik terendah yang berdekatan dengan bantaran kali, luapan air bahkan terpantau mencapai ketinggian lutut hingga pinggang orang dewasa, atau berkisar antara 40 hingga 80 sentimeter.\n\nKepala Desa setempat mengonfirmasi bahwa hingga saat ini nihil laporan mengenai korban jiwa dalam musibah tahunan tersebut. \"Alhamdulillah, untuk korban jiwa sejauh ini tidak ada. Namun, saat ini warga kami sedang bergotong-royong secara mandiri guna mengevakuasi barang-barang berharga, hewan ternak, serta dokumen penting ke tempat yang lebih tinggi karena khawatir debit air akan terus merangkak naik pada malam hari,\" ujarnya saat ditemui langsung di lokasi genangan.\n\nSelain merendam kawasan permukiman padat penduduk, banjir luapan ini juga menyebabkan akses jalan poros utama yang menghubungkan Kecamatan Sukosewu dengan wilayah sekitarnya terganggu parah. Banyak kendaraan roda dua milik warga setempat terpaksa mogok akibat nekat menerobos genangan air yang deras. Puluhan hektar lahan pertanian, terutama sawah yang baru saja ditanami padi, juga ikut terendam banjir dan terancam mengalami gagal panen jika kondisi genangan tidak kunjung surut dalam dua hari ke depan.",
    author: "M. Chanif Chaniago",
    editor: "Tim Jurnalistik",
    date: "Kamis, 21 Mei 2026",
    time: "16:30 WIB",
    category: "Berita Regional",
    region: "Bojonegoro",
    imageUrl: "https://images.pexels.com/photos/73821/flood-water-nature-natural-disaster-73821.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageCaption: "EVAKUASI BANJIR — Kondisi banjir luapan sungai yang merendam akses jalan dan pekarangan pemukiman warga di kawasan Desa Sukosewu, Kabupaten Bojonegoro, Kamis (21/5/2026).",
    bullets: [
      "Hujan lebat selama 5 jam menderas luapan Sungai Pacal.",
      "Desa Sukosewu, Klepek, dan Semawot terendam air hingga 80 cm.",
      "Puluhan hektar lahan padi rentan mengalami gagal panen jangka panjang."
    ],
    cropZoom: 1.15,
    brightness: 115,
    contrast: 110,
    saturation: 100,
    hueRotate: 0,
    rawDraft: PHOTO_ASSETS[0].defaultDraft,
    evaluationNote: "- **Perbaikan Kapitalisasi**: Bojonegoro, Sukosewu diawali huruf besar.\n- **Pemberantasan Slang**: 'bikin' -> 'mengakibatkan', 'ngungsiin' -> 'mengevakuasi'.\n- **Struktur Formal**: Mengadopsi prinsip piramida terbalik dan dateline.",
    isCustomEdited: false,
    slug: "banjir-luapan-sungai-pacal-sukosewu-bojonegoro",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-heavy-rain-falls-on-window-pane-34063-large.mp4",
    metaTitle: "Banjir Luapan Sungai Pacal Sukosewu Bojonegoro Merendam Rumah",
    metaDescription: "Hujan intensitas tinggi akibatkan luapan Sungai Pacal di Sukosewu Bojonegoro. Puluhan rumah dan hektar sawah padi terendam banjir.",
    metaKeywords: ["Bojonegoro", "Banjir", "Sungai Pacal", "Sukosewu", "Bencana Alam"]
  },
  {
    id: "unugiri_rekto",
    title: "UNUGIRI Resmikan Gedung Rektorat Baru yang Megah Berkonsep Eco-Green Tech",
    body: "BOJONEGORO — Rektorat Universitas Nahdlatul Ulama Sunan Giri (UNUGIRI) Bojonegoro secara resmi mengumumkan selesainya pembangunan gedung pusat rektorat baru yang megah dan mengadopsi struktur arsitektur hijau (eco-green). Gedung modern berlantai lima ini diharapkan mampu mengintegrasikan layanan administrasi mahasiswa secara terpadu melalui platform teknologi informasi satu pintu.\n\nGedung baru tersebut dilengkapi dengan panel surya mandiri, sistem penghematan air bersirkulasi, serta ruang ruang terbuka hijau yang asri guna mendukung visi kampus lestari. Rektor UNUGIRI menegaskan bahwa pembangunan gedung ini merupakan batu loncatan penting untuk menjadikan perguruan tinggi tersebut sebagai episentrum akademik unggul di kawasan Mataraman.",
    author: "Aditiya Wardana",
    editor: "Redaksi Kampus",
    date: "Rabu, 20 Mei 2026",
    time: "10:15 WIB",
    category: "Warta Kampus",
    region: "Bojonegoro",
    imageUrl: "https://images.pexels.com/photos/256490/pexels-photo-256490.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageCaption: "KAMPUS GREEN — Suasana gedung utama Universitas Nahdlatul Ulama Sunan Giri (UNUGIRI) Bojonegoro yang megah, ramah lingkungan, dan mendukung kenyamanan belajar mahasiswa.",
    bullets: [
      "Peresmian gedung rektorat hemat energi berbasis eco-green.",
      "Integrasi layanan administrasi satu atap interaktif.",
      "Pemasangan instalasi panel surya untuk kestabilan listrik mandiri."
    ],
    cropZoom: 1.0,
    brightness: 100,
    contrast: 100,
    saturation: 100,
    hueRotate: 0,
    rawDraft: PHOTO_ASSETS[1].defaultDraft,
    evaluationNote: "- **Perbaikan Dialek**: Mengubah slang lisan 'dapet' menjadi 'mendapatkan', 'buat' menjadi 'untuk'.\n- **EYD**: Menyempurnakan istilah serapan bahasa asing ke standarisasi bahasa Indonesia.",
    isCustomEdited: false,
    slug: "unugiri-resmikan-gedung-rektorat-baru-eco-green-tech",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-shaking-shot-of-the-building-with-architectural-lines-41584-large.mp4",
    metaTitle: "UNUGIRI Resmikan Rektorat Ramah Lingkungan Berbasis Eco-Green",
    metaDescription: "Pusat rektorat baru berlantai lima di UNUGIRI Bojonegoro resmi beroperasi dengan panel surya mandiri dan modernisasi sistem akademik berintegritas.",
    metaKeywords: ["UNUGIRI", "Rektorat", "Eco-Green", "Kampus Hijau", "Bojonegoro"]
  },
  {
    id: "opini_sampah",
    title: "Esai Opini: Peran Strategis Mahasiswa Menjaga Kelestarian Lingkungan di Bantaran Bengawan Solo Bojonegoro",
    body: "BOJONEGORO — Sebagai agen perubahan, mahasiswa memainkan peran krusial dalam menyikapi degradasi ekologis yang terjadi di bantaran perairan Bengawan Solo wilayah Bojonegoro. Menumpuknya sampah plastik dan limbah rumah tangga di sepanjang aliran sungai terpanjang di Pulau Jawa ini menuntut gerakan nyata yang terstruktur, edukatif, dan progresif.\n\nTindakan preventif berupa edukasi masyarakat, pembuatan bank sampah mandiri, serta aksi bersih sungai berkala yang digagas oleh para akademisi muda UNUGIRI, membuktikan bahwa intelektualitas mahasiswa tidak hanya bersemayam di ruang kelas namun juga membumi di tengah dinamika masyarakat sekitar wilayah Bojonegoro.",
    author: "Fathur Rohman",
    editor: "Redaktur Opini",
    date: "Selasa, 19 Mei 2026",
    time: "08:30 WIB",
    category: "Opini",
    region: "Bojonegoro",
    imageUrl: "https://images.pexels.com/photos/15750719/pexels-photo-15750719/free-photo-of-man-working-in-a-waste-recycling-center.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageCaption: "PEDULI ALAM — Aksi gotong-royong mahasiswa dalam memilah sampah guna menjaga keberlanjutan ekosistem air sungai.",
    bullets: [
      "Bengawan Solo Bojonegoro terancam polusi mikroplastik yang serius.",
      "Mahasiswa berperan sebagai inisiator pengolahan limbah organik sirkuler.",
      "Pentingnya kolaborasi taktis akademisi, pemuda, dan warga lokal."
    ],
    cropZoom: 1.05,
    brightness: 100,
    contrast: 105,
    saturation: 95,
    hueRotate: 0,
    rawDraft: "Anak-anak kuliahan harusnya ikut mikir soal sampah di Bengawan Solo Bojonegoro yg udah parah bgt. Jangan cuma teori di kelas aja tpi hrus aksi lapangan bersihin kali sama bikin bank sampah biar masyarakat ga buang sembarangan lagi.",
    evaluationNote: "- **Bahasa Ilmiah**: Slang 'anak-anak kuliahan' diganti 'mahasiswa', 'kudu' menjadi 'harus'.\n- **EYD**: Penggantian singkatan chatting 'bgt', 'tpi', 'yg' dengan kata baku.",
    isCustomEdited: false,
    slug: "peran-strategis-mahasiswa-lingkungan-bengawan-solo",
    metaTitle: "Esai Opini Peran Mahasiswa Menjaga Kelestarian Bengawan Solo",
    metaDescription: "Artikel esai opini mahasiswa UNUGIRI Bojonegoro tentang peranan mahasiswa mewujudkan reformasi ekologis dan kebersihan di Bengawan Solo.",
    metaKeywords: ["Opini", "Bengawan Solo", "Kelestarian Alam", "Mahasiswa", "Ekologi"]
  },
  {
    id: "olahraga_rektorcup",
    title: "Kejuaraan Bulu Tangkis Rektor Cup UNUGIRI Resmi Digelar, Diikuti Ratusan Atlet Se-Karesidenan",
    body: "BOJONEGORO — Unit Kegiatan Mahasiswa (UKM) Olahraga Universitas Nahdlatul Ulama Sunan Giri Bojonegoro secara resmi membuka gelaran turnamen bulu tangkis bergengsi 'Rektor Cup UNUGIRI 2026'. Kompetisi berskala luas ini diikuti oleh ratusan atlet mahasiswa terbaik dari berbagai perguruan tinggi di wilayah Karesidenan Bojonegoro dan sekitarnya.\n\nTurnamen yang diselenggarakan di GOR Kampus Terpadu UNUGIRI ini memperebutkan piala bergilir Rektor dengan total hadiah mencapai puluhan juta rupiah. Pembukaan ditandai dengan pemukulan shuttlecock pertama oleh Wakil Rektor Kemahasiswaan yang menyampaikan bahwa turnamen ini bertujuan merajut sportivitas, persaudaraan antar mahasiswa, sekaligus menjaring bibit unggul atlet nasional.",
    author: "Zaka Firmansyah",
    editor: "Redaktur Olahraga",
    date: "Senin, 18 Mei 2026",
    time: "14:00 WIB",
    category: "Olahraga",
    region: "Bojonegoro",
    imageUrl: "https://images.pexels.com/photos/3660204/pexels-photo-3660204.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageCaption: "LAPANGAN SPORT — Pertandingan sengit ganda putra di GOR UNUGIRI Bojonegoro pada babak penyisihan Rektor Cup 2026.",
    bullets: [
      "Diikuti lebih dari 150 atlet mahasiswa se-Karesidenan.",
      "GOR UNUGIRI didaulat sebagai pusat arena pertandingan berstandar BWF.",
      "Pembukaan meriah dihadiri para dewan rektorat dan perwakilan PBSI."
    ],
    cropZoom: 1.0,
    brightness: 110,
    contrast: 100,
    saturation: 110,
    hueRotate: 0,
    rawDraft: "Rektor cup unugiri buat cabor bulu tangkis rame banget hari ini. Ratusan mahasiswa sekaresidenan pada dateng buat rebutin piala bergilir pak rektor. Pertandingan di adain di gor kampus yang keliatannya oke banget.",
    evaluationNote: "- **Ejaan Geografis**: Kapitalisasi singkatan nama wilayah se-Karesidenan.\n- **Grammar Kerja**: Koreksi lisan imbuhan 'di adain' menjadi 'diselenggarakan'.",
    isCustomEdited: false,
    slug: "kejuaraan-bulutangkis-rektor-cup-unugiri-bojonegoro",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-young-man-playing-table-tennis-alone-at-home-4754-large.mp4",
    metaTitle: "Turnamen Bulu Tangkis Rektor Cup UNUGIRI Bojonegoro 2026",
    metaDescription: "Kejuaraan bergengsi bulu tangkis Rektor Cup UNUGIRI Bojonegoro resmi dibuka. Ratusan atlet mahasiswa se-Karesidenan bersaing sengit.",
    metaKeywords: ["Rektor Cup", "UNUGIRI", "Bulu Tangkis", "Olahraga", "Turnamen Mahasiswa"]
  },
  {
    id: "budaya_oklik",
    title: "Festival Tari Tradisional Oklik Bojonegoro Meriahkan Dies Natalis UNUGIRI Ke-X",
    body: "BOJONEGORO — Suasana estetik dan semarak seni tradisional menyelimuti panggung terbuka halaman rektorat Universitas Nahdlatul Ulama Sunan Giri Bojonegoro. Ribuan mahasiswa dan masyarakat umum berkumpul untuk menyaksikan Festival Musik dan Tari Oklik Tradisional Bojonegoro yang digelar guna merayakan Dies Natalis UNUGIRI yang ke-10 (X).\n\nTari Oklik merupakan warisan budaya khas Bojonegoro yang melambangkan kebersamaan, kewaspadaan ronda malam, dan harmoni sosial masyarakat agraris. Rektor UNUGIRI menyatakan bahwa komitmen pelestarian budaya daerah merupakan bentuk nyata keterikatan perguruan tinggi terhadap kekayaan sosiokultural nusantara.",
    author: "Novi Rahmawati",
    editor: "Redaktur Budaya",
    date: "Sabtu, 16 Mei 2026",
    time: "19:45 WIB",
    category: "Seni Budaya",
    region: "Bojonegoro",
    imageUrl: "https://images.pexels.com/photos/10175069/pexels-photo-10175069.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageCaption: "PENTAS BUDAYA — Penari menyuguhkan penampilan oklik khas Bojonegoro berpakaian adat yang anggun di dies natalis UNUGIRI.",
    bullets: [
      "Tari Oklik sebagai kearifan luhur Bojonegoro dipentaskan megah.",
      "Dies Natalis ke-10 mengangkat tema integritas seni dan sains nusantara.",
      "Melibatkan seniman lokal legendaris dan maestro tari daerah."
    ],
    cropZoom: 1.1,
    brightness: 105,
    contrast: 105,
    saturation: 105,
    hueRotate: 0,
    rawDraft: "Ada acara nari oklik di unugiri buat ngerayain dies natalis ke 10 kampus. Penontonnya rame pol berjubel di depan panggung halaman utama rektorat dari sore sampe malem tadi.",
    evaluationNote: "- **Gaya Penulisan**: Mengganti kata slang emosional 'rame pol' dengan 'Suasana estetik/semarak'.\n- **EYD**: Huruf kapitalisasi untuk romawi Dies Natalis UNUGIRI Ke-X.",
    isCustomEdited: false,
    slug: "festival-tari-tradisional-oklik-dies-natalis-unugiri",
    metaTitle: "Festival Tari Oklik Bojonegoro Dies Natalis UNUGIRI X",
    metaDescription: "Dies Natalis UNUGIRI Ke-10 dimeriahkan dengan pagelaran musik dan Tari Oklik khas Bojonegoro. Wadah eksibisi budaya bagi seniman muda.",
    metaKeywords: ["Tari Oklik", "Dies Natalis UNUGIRI", "Seni Budaya", "Bojonegoro", "Festival Tradisional"]
  },
  {
    id: "iptek_kebencanaan",
    title: "Inovasi Web Kebencanaan Karya Tim Informatika UNUGIRI Sukses Bantu Validasi Peringatan Dini Banjir",
    body: "BOJONEGORO — Kelompok peneliti muda dari Program Studi Teknik Informatika Universitas Nahdlatul Ulama Sunan Giri (UNUGIRI) Bojonegoro berhasil merancang sebuah aplikasi sistem informasi geografis berbasis web terintegrasi IoT untuk memonitor ketinggian air dan validasi dini bahaya banjir luapan Bengawan Solo.\n\nSistem yang dinamai 'SIA-Siaga' ini memanfaatkan teknologi sensor hulu sungai terintegrasi guna mendeteksi fluktuasi debit air secara aktual (real-time). Data sensor dikirimkan ke server utama, diproses secara cerdas, lalu disebarkan ke publik melalui SMS dan push-notif. Inovasi mahasiwa ini mendapat pujian tinggi dari BPBD Bojonegoro karena efisien memangkas rantai birokrasi peringatan dini bencana.",
    author: "Robi Darmawan",
    editor: "Redaktur Iptek",
    date: "Jumat, 15 Mei 2026",
    time: "11:00 WIB",
    category: "Iptek",
    region: "Bojonegoro",
    imageUrl: "https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageCaption: "TEKNOLOGI SIAGA — Mahasiswa mengecek kode dasbor sensor IoT kebencanaan yang memantau level air hulu sungai.",
    bullets: [
      "Aplikasi berbasis web GIS dan sensor IoT hulu air.",
      "Meringkas jalur diseminasi peringatan bencana ke warga secara masif.",
      "Hasil riset kolaboratif antara mahasiswa Informatika dan BPBD kabupaten."
    ],
    cropZoom: 1.0,
    brightness: 100,
    contrast: 100,
    saturation: 100,
    hueRotate: 0,
    rawDraft: "Anak informatika unugiri bikin sistem pendeteksi banjir keren yang dipasang sensornya di kali. Sistemnya bisa ngirim sms otomatis ke warga kalo airnya naik. Kerja sama langsung sama bpbd nih bos senggol dong.",
    evaluationNote: "- **Pensejajaran Kosakata**: Koreksi lisan slang 'bikin keren' menjadi 'berhasil merancang'.\n- **Otoritas Jurnalistik**: Membuang ekspresi sosial slang interaktif 'nih bos senggol dong' menjadi deskripsi akademik kredibel.",
    isCustomEdited: false,
    slug: "inovasi-web-kebencanaan-iot-informatika-unugiri",
    metaTitle: "Web Kebencanaan IoT SIA-Siaga Mahasiswa Informatika UNUGIRI",
    metaDescription: "Inovasi riset IoT mahasiswa Teknik Informatika UNUGIRI Bojonegoro hasilkan web SIA-Siaga pemicu peringatan dini banjir Bengawan Solo.",
    metaKeywords: ["IoT", "Informatika", "Bencana Banjir", "UNUGIRI", "Sistem Informasi Geografis"]
  }
];
